# Generated by Django 4.1.7 on 2023-04-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetApp', '0007_expense_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.PositiveSmallIntegerField(default=0.0),
        ),
    ]
