# Generated by Django 4.1.7 on 2023-04-19 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgetApp', '0008_alter_expense_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=60)),
                ('amount', models.PositiveSmallIntegerField(default=0.0)),
                ('frequency', models.PositiveSmallIntegerField(choices=[(1, 'Weekly'), (2, 'Monthly'), (3, 'Annually')], default=1)),
                ('last_updated', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='income_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='budgetApp.income'),
        ),
    ]
