# Generated by Django 4.2 on 2023-04-21 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetApp', '0010_project_end_date_project_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_date',
        ),
    ]
