# Generated by Django 4.1.7 on 2023-04-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetApp', '0011_remove_project_end_date_remove_project_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.PositiveIntegerField(max_length=6),
        ),
    ]
